version: '3.1'
services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'  # AMQP
      - '15672:15672' # rabbitmq management UI
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - bridge
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - bridge
    environment:
      - REDIS_HOST_PASSWORD=password
    volumes:
      - ./data/redis:/data

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: postgres-db
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_USER: admin
  #   ports:
  #     - 5432:5432
  #   restart: on-failure:3
  #   networks:
  #     - bridge
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # TODO: Change this
      MYSQL_USER: 'user'
      MYSQL_PASS: 'user'
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   depends_on:
  #     - mysql

networks:
  bridge:
volumes:
  data:

