name: Build Mobile Application

on:
  push:
    branches:
      - dev/mobile

jobs:
    build-android:
      runs-on: ubuntu-latest
      steps:
        - name: 🏗 Setup repo
          uses: actions/checkout@v3
      
        - name: 🏗 Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 18.x
            cache: yarn
            cache-dependency-path: ./mobile
      
        - name: 🏗 Setup EAS
          uses: expo/expo-github-action@v8
          with:
            eas-version: latest
            token: ${{ secrets.EXPO_TOKEN }}
      
        - name: 📦 Install dependencies
          run: yarn install
          working-directory: ./mobile

        - name: 🚀 Build Android
          run: eas build --platform android
          working-directory: ./mobile

    build-ios:
      runs-on: ubuntu-latest
      steps:
        - name: 🏗 Setup repo
          uses: actions/checkout@v3
      
        - name: 🏗 Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 18.x
            cache: yarn
            cache-dependency-path: ./mobile
      
        - name: 🏗 Setup EAS
          uses: expo/expo-github-action@v8
          with:
            eas-version: latest
            token: ${{ secrets.EXPO_TOKEN }}
      
        - name: 📦 Install dependencies
          run: yarn install
          working-directory: ./mobile
      
        - name: 🚀 Build Android
          run: eas build --platform ios
          working-directory: ./mobile